#!/usr/bin/env bash
#a script to install load balancer Function to install a package if not already installed

function install() {
    command -v "$1" &> /dev/null
    if [ $? -ne 0 ]; then
        echo "Installing: $1"
        sudo apt-get update -y -qq
        sudo apt-get install -y "$1" -qq
        echo "$1 installation complete"
    else
        echo "$1 is already installed."
    fi
}

# Install HAProxy
install haproxy

# Backup the default HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Configure HAProxy with roundrobin algorithm for load balancing
server_config="
defaults
    mode http
    timeout client 15s
    timeout connect 10s
    timeout server 15s
    timeout http-request 10s

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web01 [STUDENT_ID]-web-01:80 check
    server web02 [STUDENT_ID]-web-02:80 check
"

# Apply the configuration
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAProxy to start on boot
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Restart HAProxy to apply the changes
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi

echo "HAProxy configured to distribute traffic between web-01 and web-02 using roundrobin algorithm"

