#!/usr/bin/env bash
# This script installs and configures Nginx on an Ubuntu server

# Update package list and install Nginx
apt-get update -y
apt-get install nginx -y

# Create a custom HTML page containing "Holberton School"
echo 'Holberton School for the win!' > /var/www/html/index.html

# Restart nginx to apply changes
service nginx restart

# Ensure nginx start on boot
update-rc.d nginx defaults
