#!/usr/bin/env bash

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Holberton School" | sudo tee /var/www/html/index.html

#redirection config
replacement= "Sever_name _;\\
	rewrite ^/redirect_me https://github.com/Flo-renc:/ permanent;"
sudo sed -i "s|server_name _;|$replacement|" /etc/nginx/sites-available/default

sudo nginx -t
sudo service nginx start
